services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: watchfiles --filter python 'uvicorn src.main:app --host 0.0.0.0 --port 8000'